# Shared properties for mysql db
mysql: &mysql
  adapter: mysql
  socket: <%= (`uname -s` =~ /Linux/ ) ? "" :"/tmp/mysql.sock" %>
  username: root
  host: localhost
  database: rails_blog

# Shared properties for postgres.  This won't work with our schema but
# Does work with agent tests
sqlite3: &sqlite3
  adapter: sqlite3
  database: db/all.sqlite3
  pool: 5
  timeout: 5000
  host: localhost
  
common: &defaults
  <<: *sqlite3
#  <<: *mysql

# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
